server:
  port: 9527
spring:
   application:
    name: microservicecloud-zuul_gateway  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
#      defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept 
    mydept.path: /mydept/**
  ignored-services: microservicecloud-dept     #  "*"忽略所有服务
  prefix: /zhm  #设置统一前缀sss

info: 
  app.name: zhm-microservicecloud
  company.name: www.zhm.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
